name: cooking_dev

services:
  nginx:
    container_name: cw_nginx_dev
    image: nginx:1.29.3-alpine
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - cw_dev_network
    depends_on:
      - console
      - server

  console:
    container_name: cw_console_dev
    image: cw_console_dev
    restart: unless-stopped
    build:
      context: ./console
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./console:/app
      - console_node_modules:/app/node_modules
    networks:
      - cw_dev_network
    depends_on:
      - server

  server:
    container_name: cw_server_dev
    image: cw_server_dev
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    env_file: .env
    environment:
      DB_HOST: "192.168.2.99"
      DB_PORT: "5432"
      DB_NAME: cooking_dev
    volumes:
      - ./server:/code
    networks:
      - cw_dev_network
    depends_on:
      - cache

  cache:
    image: redis:7.4-alpine
    container_name: cw_redis_dev
    restart: unless-stopped
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru --save "" --appendonly no
    networks:
      - cw_dev_network

networks:
  cw_dev_network:
    driver: bridge

volumes:
  console_node_modules:
