FROM python:3.11-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  libpq-dev \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY ./app /code/app
ENTRYPOINT ["/code/entrypoint.sh"]
CMD ["gunicorn", "app.main:app", "--workers", "15", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:6666", "--log-level", "warning"]
