"""Adding Cascading delete to Recipes tables

Revision ID: 41b0b1ebd9ce
Revises: ba08389779eb
Create Date: 2025-12-28 06:08:42.215347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b0b1ebd9ce'
down_revision: Union[str, Sequence[str], None] = 'ba08389779eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
