"""unique dish name

Revision ID: 7f2e4e528ece
Revises: 946b70e36b6f
Create Date: 2025-12-27 07:35:22.433641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f2e4e528ece'
down_revision: Union[str, Sequence[str], None] = '946b70e36b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dish', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dish', type_='unique')
    # ### end Alembic commands ###
