"""fix matchchecker table

Revision ID: 946b70e36b6f
Revises: 480c2898a991
Create Date: 2025-12-26 21:50:45.076672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '946b70e36b6f'
down_revision: Union[str, Sequence[str], None] = '480c2898a991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_checker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('avoid', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('affinities', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('matches', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_checker_title'), 'match_checker', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_checker_title'), table_name='match_checker')
    op.drop_table('match_checker')
    # ### end Alembic commands ###
