"""Adding Recipe Component Name

Revision ID: ba08389779eb
Revises: 7f2e4e528ece
Create Date: 2025-12-28 05:11:25.716264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba08389779eb'
down_revision: Union[str, Sequence[str], None] = '7f2e4e528ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_component', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_component', 'name')
    # ### end Alembic commands ###
