name: Deploy prod

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, prod]
    steps:
      - name: Deploy production stack
        run: /home/mlaureti/cooking_website/scripts/deploy-prod.sh
